#!/usr/bin/env python3
"""Generate METRICS.md from runs/*/metrics.json. Usage: python3 make-metrics.py"""
import json
from pathlib import Path

LAB = Path(__file__).resolve().parent
lines = ["# Metrics", "", "Generated by make-metrics.py from runs/*/metrics.json.", "",
         "| Case | Unit | Exit | Elapsed ms | Reported tokens |", "|---|---|---:|---:|---|"]
for case in sorted((LAB / "runs").iterdir()):
    if not (case / "metrics.json").exists():
        lines.append(f"| {case.name} | — | — | — | no metrics (stopped before a measured step; see NOTE.md) |")
        continue
    for row in json.loads((case / "metrics.json").read_text()):
        usage, tokens = row.get("usage") or {}, "not measured"
        if row.get("total_tokens") is not None:
            tokens = f"total {row['total_tokens']}"
        elif usage:
            parts = [f"{k} {usage[k]}" for k in ("input_tokens", "cached_input_tokens", "output_tokens") if usage.get(k) is not None]
            tokens = ", ".join(parts) or "not measured"
        lines.append(f"| {case.name} | {row['label']} | {row['exit']} | {row['elapsed_ms']} | {tokens} |")
lines += ["", "Elapsed ms = monotonic end minus start of one subprocess. Codex agent runs report the last `usage` event",
          "of `codex exec --json`; Claude agent runs report the result event's `usage` (cache fields omitted here, kept",
          "in the raw stdout). Plain `codex exec` runs report their `tokens used` line. Deltas: N/A."]
(LAB / "METRICS.md").write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 9} rows")
