#!/usr/bin/env python3
"""Generate METRICS.md from runs/*/metrics.json and runs/*/summary.json. Usage: python3 make-metrics.py"""
import json
from pathlib import Path

LAB = Path(__file__).resolve().parent
lines = ["# Metrics", "", "Generated by make-metrics.py from runs/*/metrics.json and runs/*/summary.json.", "",
         "| Case | Step | Command | Exit | Elapsed ms | Input tokens | Cache read | Cache write | Output tokens | Cost (USD, Claude) |",
         "|---|---|---|---:|---:|---:|---:|---:|---:|---:|"]
totals = {"claude_cost": 0.0, "codex_in": 0, "codex_out": 0, "calls": 0}
for case in sorted(p for p in (LAB / "runs").iterdir() if p.is_dir()):
    summary = json.loads((case / "summary.json").read_text())
    for row in json.loads((case / "metrics.json").read_text()):
        info = summary.get(row["step"]) or {}
        tin = tout = cost = cread = cwrite = ""
        if isinstance(info, dict) and info.get("usage") and isinstance(info["usage"], dict):  # Claude
            tin, tout = info["usage"].get("input_tokens"), info["usage"].get("output_tokens")
            cread = info["usage"].get("cache_read_input_tokens")
            cwrite = info["usage"].get("cache_creation_input_tokens")
            cost = f"{info.get('cost') or 0:.4f}"
            totals["claude_cost"] += info.get("cost") or 0
        elif isinstance(info, dict) and isinstance(info.get("usage"), list) and info["usage"]:  # Codex turns
            tin = sum((u or {}).get("input_tokens", 0) for u in info["usage"])
            cread = sum((u or {}).get("cached_input_tokens", 0) for u in info["usage"])
            tout = sum((u or {}).get("output_tokens", 0) for u in info["usage"])
            totals["codex_in"] += tin
            totals["codex_out"] += tout
        totals["calls"] += 1
        argv = " ".join(str(a) for a in row["argv"][:4])
        lines.append(f"| {case.name} | {row['step']} | `{argv}` | {row['exit']} | {row['elapsed_ms']} | {tin} | {cread} | {cwrite} | {tout} | {cost} |")
lines += ["", f"{totals['calls']} calls. Claude cost total {totals['claude_cost']:.2f} USD (result `total_cost_usd`). "
          "Token definitions differ by host: Claude `input_tokens` exclude the cache columns (`cache_read_input_tokens`, "
          "`cache_creation_input_tokens`); Codex `input_tokens` include `cached_input_tokens` (shown as Cache read). "
          f"Codex input total {totals['codex_in']}, output {totals['codex_out']} (`turn.completed` usage).",
          "Elapsed ms = monotonic end minus start of one subprocess. Deltas: N/A — no comparable baseline was measured."]
(LAB / "METRICS.md").write_text("\n".join(lines) + "\n")
print(totals)
