#!/usr/bin/env python3
"""Generate METRICS.md from runs/*/metrics.json. Usage: python3 make-metrics.py"""
import json
from pathlib import Path

LAB = Path(__file__).resolve().parent
lines = ["# Metrics", "", "Generated by make-metrics.py from runs/*/metrics.json.", "",
         "| Case | Unit | Exit | Elapsed ms | Reported tokens |", "|---|---|---:|---:|---|"]
for case in sorted((LAB / "runs").iterdir()):
    for row in json.loads((case / "metrics.json").read_text()):
        tokens = []
        if row.get("input_tokens") is None and row["label"].endswith("claude"):
            try:  # the runner did not copy Claude usage into metrics.json; read it from the raw result
                usage = json.loads((case / f"{row['label']}.stdout").read_text()).get("usage") or {}
                row = dict(row, input_tokens=usage.get("input_tokens"), output_tokens=usage.get("output_tokens"))
            except (OSError, ValueError):
                pass
        if row.get("total_tokens") is not None:
            tokens.append(f"total {row['total_tokens']}")
        if row.get("input_tokens") is not None:
            tokens.append(f"in {row['input_tokens']} / out {row['output_tokens']}")
        lines.append(f"| {case.name} | {row['label']} | {row['exit']} | {row['elapsed_ms']} | {', '.join(tokens) or 'not measured'} |")
lines += ["", "Elapsed ms = monotonic end minus start of one subprocess. Codex tokens are the run's own",
          "`tokens used` line; Claude tokens are `usage.input_tokens`/`output_tokens` of the JSON result",
          "(cache tokens excluded). Deltas: N/A — no comparable baseline was measured."]
(LAB / "METRICS.md").write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 9} rows")
