#!/usr/bin/env python3
"""Generate METRICS.md from runs/*/metrics.json and runs/*/summary.json. Usage: python3 make-metrics.py"""
import json
from pathlib import Path

LAB = Path(__file__).resolve().parent
cases = sorted(p for p in (LAB / "runs").iterdir() if p.is_dir())
lines = ["# Metrics", "", "Generated by make-metrics.py from runs/*/metrics.json and runs/*/summary.json.", "",
         "| Case | Step | Command | Exit | Elapsed ms |", "|---|---|---|---:|---:|"]
calls = 0
for case in cases:
    for row in json.loads((case / "metrics.json").read_text()):
        argv = " ".join(row["argv"][:5]) + (" …" if len(row["argv"]) > 5 else "")
        lines.append(f"| {case.name} | {row['step']} | `{argv}` | {row['exit']} | {row['elapsed_ms']} |")
        calls += 1
lines += ["", "## Session results", "", "| Case | Session | Exit | Input tokens | Output tokens | Result |", "|---|---|---:|---:|---:|---|"]
for case in cases:
    summary = json.loads((case / "summary.json").read_text())
    for label, s in (summary.get("sessions") or {}).items():
        tokens = s.get("tokens") or {}
        lines.append(f"| {case.name} | {label} | {s['exit']} | {tokens.get('input')} | {tokens.get('output')} | {s.get('result')} |")
lines += ["", f"{calls} calls. Elapsed ms = monotonic end minus start of one subprocess. Session tokens are the",
          "stream-json result's `usage.input_tokens`/`output_tokens` (no credentials, so no model call).",
          "Deltas: N/A — no comparable baseline was measured."]
(LAB / "METRICS.md").write_text("\n".join(lines) + "\n")
print(f"{calls} calls")
