#!/usr/bin/env python3
"""Generate METRICS.md from runs/*/metrics.json. Usage: python3 make-metrics.py"""
import json
from pathlib import Path

LAB = Path(__file__).resolve().parent
lines = ["# Metrics", "", "Generated by make-metrics.py from runs/*/metrics.json.", "",
         "| Case | Step | Command | Exit | Elapsed ms |", "|---|---|---|---:|---:|"]
for case in sorted(p for p in (LAB / "runs").iterdir() if p.is_dir()):
    for row in json.loads((case / "metrics.json").read_text()):
        argv = " ".join(row["argv"][:5]) + (" …" if len(row["argv"]) > 5 else "")
        lines.append(f"| {case.name} | {row['step']} | `{argv}` | {row['exit']} | {row['elapsed_ms']} |")
lines += ["", "Elapsed ms = monotonic end minus start of one subprocess. No model calls, so no tokens.",
          "Deltas: N/A — no comparable baseline was measured."]
(LAB / "METRICS.md").write_text("\n".join(lines) + "\n")
print(f"{len(lines) - 9} rows")
